/**
 * Global shared domain types.
 * Component-specific types live with their components.
 * Server/DB types are generated by Prisma and re-exported from `@/server/db`.
 */

export type ID = string;
export type Slug = string;
export type ISODateString = string;

export type Currency = "USD" | "PKR" | "EUR" | "GBP";

export interface Money {
  amount: number;
  currency: Currency;
}

export type ProductStatus = "DRAFT" | "ACTIVE" | "ARCHIVED" | "DISCONTINUED";
export type OrderStatus =
  | "PENDING"
  | "PROCESSING"
  | "SHIPPED"
  | "DELIVERED"
  | "CANCELLED"
  | "REFUNDED"
  | "FAILED";
export type PaymentStatus =
  | "PENDING"
  | "PROCESSING"
  | "PAID"
  | "FAILED"
  | "REFUNDED"
  | "PARTIALLY_REFUNDED";
export type PaymentProvider = "STRIPE" | "JAZZCASH" | "EASYPISA" | "MOCK";
export type UserRole = "CUSTOMER" | "ADMIN" | "TRADE";
export type ShippingMethod = "STANDARD" | "EXPRESS" | "WHITE_GLOVE";

export interface Address {
  firstName: string;
  lastName: string;
  line1: string;
  line2?: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  phone?: string;
}

export interface AnalyticsEvent {
  id: ID;
  event: string;
  userId?: ID;
  anonymousId?: string;
  properties: Record<string, unknown>;
  timestamp: ISODateString;
  sessionId?: string;
}
